### ISSUE TITLE
Unable to install all dependencies  on centos 7 for PolisServer

### ISSUE THREAD

**Issue by uzzal2k5** [pol-is/issues#102]
Hi, I am trying to install and configure polisServer on centos 7 minimul where 'uname -a'

>` Linux polis 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
 
After giving command `npm install   ` getting following error.

Log outpu are given bellow. PLz review the error and help me to get out from this issue

```
> [root@polis polisServer]# npm install
> npm WARN deprecated mimelib@0.2.19: This project is unmaintained
> npm WARN deprecated mongodb@2.0.46: Please upgrade to 2.2.19 or higher
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> 
> > libpq@1.8.7 install /root/polisServer/node_modules/libpq
> > node-gyp rebuild
> 
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
> make: Entering directory `/root/polisServer/node_modules/libpq/build'
>   CXX(target) Release/obj.target/addon/src/connection.o
> make: g++: Command not found
> make: *** [Release/obj.target/addon/src/connection.o] Error 127
> make: Leaving directory `/root/polisServer/node_modules/libpq/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 3.10.0-693.el7.x86_64
> gyp ERR! command "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/polisServer/node_modules/libpq
> gyp ERR! node -v v6.11.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm WARN request@2.12.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
> npm WARN polis@0.0.0 No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the libpq@1.8.7 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-04-17T09_51_22_831Z-debug.log
> 
```

tail -n 100 /root/.npm/_logs/2018-04-17T09_51_22_831Z-debug.log
```
silly saveTree │   ├── isarray@1.0.0
1302 silly saveTree │   └── string_decoder@1.1.1
1302 silly saveTree ├── request-promise@3.0.0
1302 silly saveTree ├── request@2.85.0
1302 silly saveTree ├── response-time@2.3.1
1302 silly saveTree ├─┬ simple-oauth2@0.2.1
1302 silly saveTree │ ├── date-utils@1.2.21
1302 silly saveTree │ ├── querystring@0.1.0
1302 silly saveTree │ └─┬ request@2.12.0
1302 silly saveTree │   ├─┬ form-data@0.0.3
1302 silly saveTree │   │ ├── async@0.1.9
1302 silly saveTree │   │ ├─┬ combined-stream@0.0.3
1302 silly saveTree │   │ │ └── delayed-stream@0.0.5
1302 silly saveTree │   │ └── mime@1.2.2
1302 silly saveTree │   └── mime@1.2.7
1302 silly saveTree ├─┬ sql@0.34.0
1302 silly saveTree │ ├── lodash@1.3.1
1302 silly saveTree │ └── sliced@0.0.5
1302 silly saveTree ├─┬ stripe@2.5.5
1302 silly saveTree │ └── when@2.4.0
1302 silly saveTree ├── underscore@1.8.3
1302 silly saveTree ├── valid-url@1.0.9
1302 silly saveTree └─┬ winston@1.0.2
1302 silly saveTree   ├── async@1.0.0
1302 silly saveTree   └── colors@1.0.3
1303 warn request@2.12.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
1304 warn polis@0.0.0 No license field.
1305 verbose stack Error: libpq@1.8.7 install: `node-gyp rebuild`
1305 verbose stack Exit status 1
1305 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
1305 verbose stack     at emitTwo (events.js:106:13)
1305 verbose stack     at EventEmitter.emit (events.js:191:7)
1305 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1305 verbose stack     at emitTwo (events.js:106:13)
1305 verbose stack     at ChildProcess.emit (events.js:191:7)
1305 verbose stack     at maybeClose (internal/child_process.js:891:16)
1305 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
1306 verbose pkgid libpq@1.8.7
1307 verbose cwd /root/polisServer
1308 verbose Linux 3.10.0-693.el7.x86_64
1309 verbose argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "install"
1310 verbose node v6.11.1
1311 verbose npm  v5.8.0
1312 error code ELIFECYCLE
1313 error errno 1
1314 error libpq@1.8.7 install: `node-gyp rebuild`
1314 error Exit status 1
1315 error Failed at the libpq@1.8.7 install script.
1315 error This is probably not a problem with npm. There is likely additional logging output above.
1316 verbose exit [ 1, true ]
```

**Comment by metasoarous** [comment]
Hi @uzzal2k5. I see somewhere in there it says `g++: Command not found`. Seems like it's missing some basic build utilities? I don't know anything about centos, but with Ubuntu I think you can get that from the `build-essential` package, installed with `sudo apt-get install build-essential`. If you manage to get some version of that installed, you should be able to move forward.

**Comment by metasoarous** [comment]
Assuming you got through this and closing now.

**Comment by uzzal2k5** [comment]
@metasoarous thank you. I make different way out rather than centos or ubuntu. I faced similar problem with both of them. So I take another way to ensure node environment and install all required packages

**Comment by metasoarous** [comment]
Great; Glad to hear it. Like I said, if you're able to share your containerization work, we'd greatly appreciate the contribution.
